# Generated by Django 3.2.4 on 2021-06-16 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('InfBooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='book',
            name='date_issue',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи книги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='date_return',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата возврата книги'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(to='InfBooks.Book'),
        ),
    ]
