# Generated by Django 3.2.4 on 2021-06-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfBooks', '0002_auto_20210616_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_issue',
            field=models.DateTimeField(blank=True, verbose_name='Дата выдачи книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_return',
            field=models.DateTimeField(blank=True, verbose_name='Дата возврата книги'),
        ),
    ]
