# Generated by Django 3.2.4 on 2021-06-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfBooks', '0004_auto_20210616_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='authors', to='InfBooks.Book'),
        ),
    ]
