# Generated by Django 3.2.4 on 2021-06-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfBooks', '0005_alter_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.ManyToManyField(related_name='book', to='InfBooks.Author'),
        ),
    ]
