# Generated by Django 3.2.4 on 2021-06-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfBooks', '0007_rename_book_book_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='InfBooks.Author'),
        ),
    ]
